Class {
	#name : #CATabPixelFeature,
	#superclass : #CATabFeature,
	#category : #ComputationalArt2
}

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'Tyron Franzke 7/10/2024 12:57'
}
CATabPixelFeature class >> featureName [
	^'tab-pixel'.
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'Tyron Franzke 7/10/2024 12:58'
}
CATabPixelFeature class >> tabName [
	^ 'pixel'.
]
