Class {
	#name : #CATabInitalizeFeature,
	#superclass : #CATabFeature,
	#category : #ComputationalArt2
}

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'Tyron Franzke 7/10/2024 12:57'
}
CATabInitalizeFeature class >> featureName [
	^'tab-initialize'.
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'Tyron Franzke 7/10/2024 12:57'
}
CATabInitalizeFeature class >> tabName [
	^'initialize'.
]
