Class {
	#name : #CATabPixelFeature,
	#superclass : #CATabFeature,
	#category : #ComputationalArt2
}

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'Yoan Tchorenev 7/10/2024 13:33'
}
CATabPixelFeature class >> featureName [
	^'Pixel Script'.
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'Tyron Franzke 7/10/2024 12:58'
}
CATabPixelFeature class >> tabName [
	^ 'pixel'.
]
